# Generated by Django 5.2.7 on 2025-11-03 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_tags_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTags',
            fields=[
                ('pk', models.CompositePrimaryKey('asset', 'tag', blank=True, editable=False, primary_key=True, serialize=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.tags')),
            ],
        ),
    ]
