# Generated by Django 5.2.7 on 2025-11-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_assettags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetTags',
        ),
    ]
