# Generated by Django 5.2.7 on 2025-11-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_delete_assettags'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(to='asset.tags'),
        ),
    ]
