# Generated by Django 5.2.7 on 2025-11-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_alter_asset_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='asset.tags'),
        ),
    ]
