# Generated by Django 5.2.7 on 2025-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_alter_asset_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='version_no',
            field=models.IntegerField(default=1),
        ),
    ]
